defaultSemverRangePrefix: ""

enableScripts: false

globalFolder: ${HOME}/.cache/yarn

networkConcurrency: 1024

packageExtensions:
  # Issue: antfu/local-pkg#2
  local-pkg@*:
    peerDependencies:
      vitest: "*"
