packageExtensions:
  express-openapi-validator@*:
    dependencies:
      express: "*"
  jest-config@*:
    dependencies:
      ts-node: "*"
      typescript: "*"
  react-switch-selector@*:
    dependencies:
      csstype: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
