defaultSemverRangePrefix: ""

enableScripts: false

networkConcurrency: 1024

packageExtensions:
  "@mui/x-charts@*":
    dependencies:
      "@mui/utils": "*"
  "@nivo/core@*":
    dependencies:
      "@types/prop-types": "*"
      "@types/react": "*"
      prop-types: "*"
      react: "*"
  express-openapi-validator@*:
    dependencies:
      express: "*"
  local-pkg@*:
    dependencies:
      vitest: "*"
  react-switch-selector@*:
    dependencies:
      csstype: "*"
