defaultSemverRangePrefix: ""

enableScripts: false

globalFolder: /root/.cache/yarn

networkConcurrency: 1024

packageExtensions:
  # fixed upstream, waiting for release in v7
  "@mui/x-charts@*":
    peerDependencies:
      "@mui/utils": "*"
  # Issue: plouc/nivo#2401
  "@nivo/arcs@*":
    peerDependencies:
      prop-types: "*"
  "@nivo/sunburst@*":
    peerDependencies:
      prop-types: "*"
  "@nivo/tooltip@*":
    peerDependencies:
      prop-types: "*"
      react: "*"
  # PR: cdimascio/express-openapi-validator#907
  express-openapi-validator@*:
    peerDependencies:
      express: "*"
  # Issue: antfu/local-pkg#2
  local-pkg@*:
    peerDependencies:
      vitest: "*"
