packageExtensions:
  es-iterator-helpers@*:
    dependencies:
      call-bind: "*"
      define-properties: "*"
      get-intrinsic: "*"
      has-property-descriptors: "*"
  express-openapi-validator@*:
    dependencies:
      express: "*"
  local-pkg@*:
    dependencies:
      vitest: "*"
  react-switch-selector@*:
    dependencies:
      csstype: "*"
  vite-plugin-top-level-await@*:
    dependencies:
      rollup: "*"
  vite-tsconfig-paths@*:
    dependencies:
      vite: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.2.cjs
