defaultSemverRangePrefix: ""

enableScripts: false

globalFolder: ${HOME}/.cache/yarn

networkConcurrency: 1024

packageExtensions:
  # PR: cdimascio/express-openapi-validator#907
  express-openapi-validator@*:
    peerDependencies:
      express: "*"
  # Issue: antfu/local-pkg#2
  local-pkg@*:
    peerDependencies:
      vitest: "*"
