packageExtensions:
  express-openapi-validator@*:
    dependencies:
      express: "*"
  react-switch-selector@*:
    dependencies:
      csstype: "*"
  vite-tsconfig-paths@*:
    dependencies:
      vite: "*"
  local-pkg@*:
    dependencies:
      "@vitest/coverage-istanbul": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

# Make sure yarnPath is the last line of this file
yarnPath: .yarn/releases/yarn-3.4.1.cjs
