packageExtensions:
  es-iterator-helpers@*:
    dependencies:
      call-bind: "*"
      define-properties: "*"
      get-intrinsic: "*"
      has-property-descriptors: "*"
  express-openapi-validator@*:
    dependencies:
      express: "*"
  local-pkg@*:
    dependencies:
      vitest: "*"
  react-switch-selector@*:
    dependencies:
      csstype: "*"
  vite-plugin-top-level-await@*:
    dependencies:
      rollup: "*"
  vite-tsconfig-paths@*:
    dependencies:
      vite: "*"

compressionLevel: mixed
defaultSemverRangePrefix: ""
networkConcurrency: 1024
