defaultSemverRangePrefix: ""

enableScripts: false

networkConcurrency: 1024

packageExtensions:
  express-openapi-validator@*:
    dependencies:
      express: "*"
  local-pkg@*:
    dependencies:
      vitest: "*"
  react-switch-selector@*:
    dependencies:
      csstype: "*"
