FROM node:19.7.0-alpine as test
ENV FORCE_COLOR true
ENV DOMAIN example.com
ENV SUBDOMAIN subdomain
ENV SIGNAL_URL http://127.0.0.1:8080
ENV SIGNAL_SENDER +493012345678

WORKDIR /workdir

COPY . .

RUN \
  yarn workspace rating-tracker-commons build && \
  yarn test

ENTRYPOINT [ "/bin/sh" ]
