FROM node:20.1.0-alpine as yarn
ENV FORCE_COLOR true

WORKDIR /workdir

# Copy files required for installing dependencies
COPY global ./global
COPY .yarn ./.yarn
COPY package.json .yarnrc.yml yarn.lock ./
COPY packages/backend/package.json ./packages/backend/
COPY packages/commons/package.json ./packages/commons/
COPY packages/frontend/package.json ./packages/frontend/

# Install dependencies
RUN yarn --immutable

# Copy files required for Prisma
COPY packages/backend/prisma ./packages/backend/prisma
COPY packages/backend/test/.env ./packages/backend/test/

# Initialize Prisma for tests and generate client
RUN yarn workspace @rating-tracker/backend test:prisma:migrate:init

ENTRYPOINT [ "/bin/sh" ]
