FROM node:19.8.1-alpine as yarn
ENV FORCE_COLOR true

WORKDIR /workdir

COPY . .
RUN \
  yarn --immutable && \
  yarn workspace rating-tracker-backend test:prisma:migrate:init

ENTRYPOINT [ "/bin/sh" ]
