FROM node:19.3.0-alpine3.16 as test
ENV FORCE_COLOR true
ENV DOMAIN example.com
ENV SUBDOMAIN subdomain
ENV SIGNAL_URL http://127.0.0.1:8080
ENV SIGNAL_SENDER +493012345678
ENV SIGNAL_RECIPIENT "+4915101234567 +4915201234567"

WORKDIR /app

COPY . .
RUN yarn workspace rating-tracker-commons build
RUN yarn test

ENTRYPOINT [ "/bin/sh" ]