import { Stock } from "./models/stock.js";

const exampleStocks: Stock[] = [
  {
    ticker: "exampleALV",
    name: "Allianz SE",
    country: "DE",
    industry: "InsuranceDiversified",
    size: "Large",
    style: "Value",
    morningstarId: "0P00009QNO",
    morningstarLastFetch: new Date("2022-10-29T14:15:31.749Z"),
    starRating: 4,
    dividendYieldPercent: 5.99,
    priceEarningRatio: 18.76,
  },
  {
    ticker: "exampleAAPL",
    name: "Apple Inc",
    country: "US",
    industry: "ConsumerElectronics",
    size: "Large",
    style: "Growth",
    morningstarId: "0P000000GY",
    morningstarLastFetch: new Date("2022-10-29T14:16:11.079Z"),
    starRating: 2,
    dividendYieldPercent: 0.58,
    priceEarningRatio: 25.51,
  },
  {
    ticker: "exampleBN",
    name: "Danone SA",
    country: "FR",
    industry: "PackagedFoods",
    size: "Large",
    style: "Blend",
    morningstarId: "0P00009WEL",
    morningstarLastFetch: new Date("2022-10-29T14:15:59.590Z"),
    starRating: 4,
    dividendYieldPercent: 3.9,
    priceEarningRatio: 20.33,
  },
  {
    ticker: "exampleIBE",
    name: "Iberdrola SA",
    country: "ES",
    industry: "UtilitiesDiversified",
    size: "Large",
    style: "Blend",
    morningstarId: "0P0000A4Z3",
    morningstarLastFetch: new Date("2022-10-29T14:15:37.388Z"),
    starRating: 3,
    dividendYieldPercent: 4.34,
    priceEarningRatio: 14.88,
  },
  {
    ticker: "exampleKGX",
    name: "Kion Group AG",
    country: "DE",
    industry: "FarmHeavyConstructionMachinery",
    size: "Mid",
    style: "Value",
    morningstarId: "0P0000Z3A6",
    morningstarLastFetch: new Date("2022-10-29T14:16:07.363Z"),
    starRating: 5,
    dividendYieldPercent: 6.68,
    priceEarningRatio: 6.7,
  },
  {
    ticker: "exampleMELI",
    name: "MercadoLibre Inc",
    country: "AR",
    industry: "InternetRetail",
    size: "Large",
    style: "Growth",
    morningstarId: "0P00009FL7",
    morningstarLastFetch: new Date("2022-10-29T14:15:42.406Z"),
    starRating: 4,
    priceEarningRatio: 188.68,
  },
  {
    ticker: "exampleNEM",
    name: "Newmont Corp",
    country: "US",
    industry: "Gold",
    size: "Mid",
    style: "Value",
    morningstarId: "0P000003WE",
    morningstarLastFetch: new Date("2022-10-29T14:16:18.736Z"),
    dividendYieldPercent: 5.13,
    priceEarningRatio: 45.66,
  },
  {
    ticker: "exampleNOVO B",
    name: "Novo Nordisk A/S",
    country: "DK",
    industry: "Biotechnology",
    size: "Large",
    style: "Growth",
    morningstarId: "0P0000A5BQ",
    morningstarLastFetch: new Date("2022-10-29T14:15:55.674Z"),
    starRating: 3,
    dividendYieldPercent: 1.37,
    priceEarningRatio: 36.76,
  },
  {
    ticker: "exampleNULL",
    name: "Null Inc",
  },
  {
    ticker: "exampleORSTED",
    name: "Ørsted A/S",
    country: "DK",
    industry: "UtilitiesRenewable",
    size: "Large",
    style: "Blend",
    morningstarId: "0P0001846T",
    morningstarLastFetch: new Date("2022-10-29T14:16:03.739Z"),
    starRating: 5,
    dividendYieldPercent: 1.99,
    priceEarningRatio: 28.49,
  },
  {
    ticker: "exampleTSM",
    name: "Taiwan Semiconductor Manufacturing Co Ltd",
    country: "TW",
    industry: "Semiconductors",
    size: "Large",
    style: "Blend",
    morningstarId: "0P000005AR",
    morningstarLastFetch: new Date("2022-10-29T14:16:14.871Z"),
    starRating: 5,
    dividendYieldPercent: 3.04,
    priceEarningRatio: 13.57,
  },
];

export default exampleStocks;
