-- AlterTable
ALTER TABLE "Stock" ADD COLUMN     "prices1mo" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "prices1y" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "yahooLastFetch" TIMESTAMP(6);

