version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    image: dev-env/nginx
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server
    restart: unless-stopped
    user: "1000"
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      REDIS_ARGS: "--save 60 1 --appendonly yes --no-appendfsync-on-rewrite yes --aclfile /etc/redis/users.acl"
    volumes:
      - ./redis/data:/data
      - ./redis/config:/etc/redis

  postgres: # On macOS, this container requires gRPC FUSE instead of VirtioFS until docker/for-mac#6614 is resolved.
    image: postgres:alpine
    restart: unless-stopped
    user: ${MY_UID}:${MY_GID}
    cap_drop:
      - all
    cap_add:
      - CHOWN
    security_opt:
      - no-new-privileges
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: "rating-tracker"
      POSTGRES_USER: "rating-tracker"
      POSTGRES_PASSWORD_FILE: /var/lib/postgresql/pgpass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/pgpass:/var/lib/postgresql/pgpass
    shm_size: '256mb'

  selenium:
    image: seleniarm/standalone-chromium:latest
    restart: unless-stopped
    environment:
      - SE_NODE_MAX_SESSIONS=4
      # - START_XVFB=false
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ports:
      - "127.0.0.1:4444:4444"
    shm_size: '2gb'

  signal:
    image: bbernhard/signal-cli-rest-api
    environment:
      - MODE=native
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./signal-cli:/home/.local/share/signal-cli
