FROM node:20.6.1-alpine as validator
ENV FORCE_COLOR true

WORKDIR /workdir

# Copy project files and WebAssembly package
COPY --from=marvinruder/rating-tracker:wasm /workdir/pkg packages/wasm
COPY . .

# Run validations
RUN yarn validate

FROM node:20.6.1-alpine as build
LABEL stage=build
ENV NODE_ENV production
ENV FORCE_COLOR true

WORKDIR /workdir

# Copy project files as well as Swagger UI files and WebAssembly package
COPY --from=marvinruder/rating-tracker:wasm /workdir/pkg packages/wasm
COPY \
  .yarn/unplugged/swagger-ui-dist-*/node_modules/swagger-ui-dist/swagger-ui.css \
  .yarn/unplugged/swagger-ui-dist-*/node_modules/swagger-ui-dist/swagger-ui-bundle.js \
  .yarn/unplugged/swagger-ui-dist-*/node_modules/swagger-ui-dist/swagger-ui-standalone-preset.js \
  /workdir/app/public/api-docs/
COPY . .

RUN \
  # Build Node.js bundle
  yarn build && \
  # Parse Node.js bundle
  /bin/sh -c 'cd packages/backend && EXIT_AFTER_READY=1 node -r ./test/env.ts dist/server.mjs' && \
  # Create directories for target container and copy only necessary files
  mkdir -p app/public app/prisma/client && \
  cp packages/backend/dist/server.mjs app && \
  cp -r packages/backend/prisma/client/schema.prisma packages/backend/prisma/client/libquery_engine-* app/prisma/client && \
  cp -r packages/frontend/dist/* app/public

# Add eslint cache
COPY --from=validator /workdir/.eslintcache .

ENTRYPOINT [ "/bin/sh" ]
