FROM scratch
COPY --from=rust:1.75.0-alpine /etc/os-release /etc/os-release-rust
COPY --from=alpine:3.19.1 /etc/os-release /etc/os-release-alpine
COPY --from=node:21.6.1-alpine /etc/os-release /etc/os-release-node
