FROM scratch
COPY --from=alpine:3.18.3 /etc/os-release /etc/os-release-alpine
COPY --from=node:20.5.1-alpine /etc/os-release /etc/os-release-node
COPY --from=eclipse-temurin:17.0.8_7-jre-jammy /etc/os-release /etc/os-release-java
COPY --from=rust:1.71.1-alpine /etc/os-release /etc/os-release-rust
COPY --from=postgres:alpine /etc/os-release /etc/os-release-postgres
COPY --from=redis:alpine /etc/os-release /etc/os-release-redis
