FROM node:20.5.0-alpine as build
LABEL stage=build
ENV NODE_ENV production
ENV FORCE_COLOR true

WORKDIR /workdir

# Copy project files and WebAssembly package
COPY . .
COPY --from=marvinruder/rating-tracker:wasm /workdir/pkg packages/wasm

# Build Node.js bundle
RUN yarn build

# Create directories for target container and copy only necessary files
RUN mkdir -p app/packages/backend/public app/packages/backend/dist/prisma/client && \
  cp -r packages/backend/dist app/packages/backend && \
  cp -r packages/backend/prisma/client/schema.prisma packages/backend/prisma/client/libquery_engine-* app/packages/backend/dist/prisma/client && \
  cp -r packages/frontend/dist/* app/packages/backend/public

ENTRYPOINT [ "/bin/sh" ]
