FROM rust:1.71.1-alpine

WORKDIR /workdir

RUN --mount=type=cache,target=/var/cache/apk apk add wasm-pack binaryen pkgconfig openssl-dev
RUN rustup target add wasm32-unknown-unknown

COPY wasm/Cargo.toml .
COPY wasm/Cargo.lock .
COPY wasm/config.toml .

RUN \
  mkdir ./src && echo 'pub fn tmp() {}' > ./src/lib.rs && \
  wasm-pack build --release && \
  rm -r ./src/lib.rs ./target/wasm32-*/release/wasm.*

COPY wasm/src/* ./src/

RUN \
  touch ./src/* && \
  wasm-pack build -s rating-tracker --release && \
  sed -E -i.bak 's/"module": "([A-Za-z0-9\-\.]+)",/"main": "\1",\n  "module": "\1",/g ; s/^}$/}\n/' pkg/package.json && \
  rm pkg/package.json.bak

ENTRYPOINT [ "/bin/sh" ]
