FROM node:20.7.0-alpine as yarn
ENV FORCE_COLOR true

WORKDIR /workdir

# Copy files required for installing dependencies
COPY cache/yarn/global ./cache/yarn/global
COPY .yarn ./.yarn

# Install dependencies
RUN \
  --mount=type=bind,source=package.json,target=package.json \
  --mount=type=bind,source=.yarnrc.yml,target=.yarnrc.yml \
  --mount=type=bind,source=yarn.lock,target=yarn.lock \
  --mount=type=bind,source=packages/backend/package.json,target=packages/backend/package.json \
  --mount=type=bind,source=packages/commons/package.json,target=packages/commons/package.json \
  --mount=type=bind,source=packages/frontend/package.json,target=packages/frontend/package.json \
  --mount=type=bind,source=packages/wasm/package.json,target=packages/wasm/package.json \
  yarn --immutable

# Generate Prisma client
COPY packages/backend/prisma ./packages/backend/prisma
RUN \
  --mount=type=bind,source=package.json,target=package.json \
  --mount=type=bind,source=.yarnrc.yml,target=.yarnrc.yml \
  --mount=type=bind,source=yarn.lock,target=yarn.lock \
  --mount=type=bind,source=packages/backend/package.json,target=packages/backend/package.json \
  --mount=type=bind,source=packages/commons/package.json,target=packages/commons/package.json \
  --mount=type=bind,source=packages/frontend/package.json,target=packages/frontend/package.json \
  --mount=type=bind,source=packages/wasm/package.json,target=packages/wasm/package.json \
  yarn workspace @rating-tracker/backend prisma:generate

ENTRYPOINT [ "/bin/sh" ]
