FROM scratch
COPY --from=postgres:alpine /etc/os-release /etc/os-release-postgres
COPY --from=redis:alpine /etc/os-release /etc/os-release-redis
COPY --from=node:20.5.1-alpine /etc/os-release /etc/os-release-node
COPY --from=eclipse-temurin:17.0.8_7-jre-jammy /etc/os-release /etc/os-release-java
