FROM scratch
COPY --from=rust:1.74.1-alpine /etc/os-release /etc/os-release-rust
COPY --from=alpine:3.19.0 /etc/os-release /etc/os-release-alpine
COPY --from=node:21.4.0-alpine /etc/os-release /etc/os-release-node
