FROM node:20.5.0-alpine as test
ENV FORCE_COLOR true
ENV DOMAIN example.com
ENV SUBDOMAIN subdomain
ENV SIGNAL_URL http://127.0.0.1:8080
ENV SIGNAL_SENDER +493012345678

WORKDIR /workdir

COPY . .

RUN \
  yarn workspace @rating-tracker/commons build && \
  yarn test

FROM eclipse-temurin:17-jre-ubi9-minimal

RUN \
  bash <(curl -Ls https://coverage.codacy.com/get.sh) download && \
  mkdir -p /coverage/{backend,commons,frontend}

WORKDIR /coverage

COPY --from=test /workdir/packages/backend/coverage/. /coverage/backend/.
COPY --from=test /workdir/packages/commons/coverage/. /coverage/commons/.
COPY --from=test /workdir/packages/frontend/coverage/. /coverage/frontend/.

ENTRYPOINT "bash <(curl -Ls https://coverage.codacy.com/get.sh)"
