FROM node:20.6.0-alpine as yarn
ENV FORCE_COLOR true

WORKDIR /workdir

# Copy files required for installing dependencies
COPY global ./global
COPY .yarn ./.yarn
COPY package.json .yarnrc.yml yarn.lock ./
COPY packages/backend/package.json ./packages/backend/
COPY packages/commons/package.json ./packages/commons/
COPY packages/frontend/package.json ./packages/frontend/
COPY packages/wasm/package.json ./packages/wasm/

# Install dependencies
RUN yarn --immutable

# Generate Prisma client
COPY packages/backend/prisma ./packages/backend/prisma
RUN yarn workspace @rating-tracker/backend prisma:generate

ENTRYPOINT [ "/bin/sh" ]
