FROM node:20.6.1-alpine as test
ENV FORCE_COLOR true
ENV DOMAIN example.com
ENV SUBDOMAIN subdomain
ENV SIGNAL_URL http://127.0.0.1:8080
ENV SIGNAL_SENDER +493012345678

WORKDIR /workdir

# Copy project files and WebAssembly package
COPY --from=marvinruder/rating-tracker:wasm /workdir/pkg packages/wasm
COPY . .

# Run tests
RUN yarn test

FROM eclipse-temurin:17.0.8_7-jre-jammy as codacy

# Download and extract Codacy coverage reporter
RUN \
  curl -Ls https://coverage.codacy.com/get.sh > /usr/local/bin/codacy-coverage && \
  chmod +x /usr/local/bin/codacy-coverage && \
  codacy-coverage download && \
  mkdir -p /coverage/{backend,commons,frontend}

WORKDIR /coverage

# Copy coverage reports from test stage
COPY --from=test /workdir/packages/backend/coverage/. /coverage/backend/.
COPY --from=test /workdir/packages/commons/coverage/. /coverage/commons/.
COPY --from=test /workdir/packages/frontend/coverage/. /coverage/frontend/.

ENTRYPOINT [ "codacy-coverage" ]
