[package]
name = "wasm"
version = "3.1.1"
authors = ["Marvin A. Ruder <ratingtracker@mruder.dev>"]
description = "A collection of utilities written in Rust and compiled to WebAssembly"
license = "MIT"
repository = "https://github.com/marvinruder/rating-tracker"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "=0.21.7"
console_error_panic_hook = "=0.1.7"
image = "=0.24.7"
kamadak-exif = "=0.5.5"
wasm-bindgen = "=0.2.89"

[profile.release]
opt-level = 'z'
strip = 'symbols'
lto = true
panic = 'abort'
codegen-units = 1
