[package]
name = "wasm"
version = "4.3.1"
authors = ["Marvin A. Ruder <ratingtracker@mruder.dev>"]
description = "A collection of utilities written in Rust and compiled to WebAssembly"
license = "MIT"
repository = "https://github.com/marvinruder/rating-tracker"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "=0.1.7"
image = { version = "=0.24.9", default-features = false, features = [
  "jpeg",
  "png",
  "tiff",
  "avif-encoder",
] }
kamadak-exif = "=0.5.5"
wasm-bindgen = "=0.2.91"

[profile.release]
opt-level = 'z'
strip = 'symbols'
lto = true
panic = 'abort'
codegen-units = 1
