import { Country, countryArray } from "./Country.js";

/**
 * An array of region identifiers.
 */
export const regionArray = [
  "NorthAmerica",
  "LatinAmerica",
  "UnitedKingdom",
  "Eurozone",
  "EuropeDeveloped",
  "EuropeEmerging",
  "AfricaME",
  "Japan",
  "Australasia",
  "AsiaDeveloped",
  "AsiaEmerging",
] as const;

/**
 * A region.
 */
export type Region = (typeof regionArray)[number];

/**
 * Checks if a string is a valid region.
 *
 * @param {string} s The string to check.
 * @returns {boolean} True if the string is a valid region.
 */
export function isRegion(s: string): s is Region {
  return regionArray.includes(s as Region);
}

/**
 * A record of region names for each region.
 */
export const regionName: Record<Region, string> = {
  NorthAmerica: "North America",
  LatinAmerica: "Latin America",
  UnitedKingdom: "United Kingdom",
  Eurozone: "Eurozone",
  EuropeDeveloped: "Europe Developed ex Euro",
  EuropeEmerging: "Europe Emerging",
  AfricaME: "Africa/Middle East",
  Japan: "Japan",
  Australasia: "Australasia",
  AsiaDeveloped: "Asia Developed",
  AsiaEmerging: "Asia Emerging",
};

/**
 * A record associating each country with its region.
 */
export const regionOfCountry: Record<Country, Region> = {
  US: "NorthAmerica",
  CA: "NorthAmerica",
  PM: "NorthAmerica",
  UM: "NorthAmerica",
  AI: "LatinAmerica",
  AG: "LatinAmerica",
  AR: "LatinAmerica",
  AW: "LatinAmerica",
  BS: "LatinAmerica",
  BB: "LatinAmerica",
  BZ: "LatinAmerica",
  BM: "LatinAmerica",
  BO: "LatinAmerica",
  BQ: "LatinAmerica",
  BR: "LatinAmerica",
  VG: "LatinAmerica",
  KY: "LatinAmerica",
  CL: "LatinAmerica",
  CO: "LatinAmerica",
  CR: "LatinAmerica",
  CU: "LatinAmerica",
  CW: "LatinAmerica",
  DM: "LatinAmerica",
  DO: "LatinAmerica",
  EC: "LatinAmerica",
  SV: "LatinAmerica",
  FK: "LatinAmerica",
  GF: "LatinAmerica",
  GD: "LatinAmerica",
  GP: "LatinAmerica",
  GT: "LatinAmerica",
  GY: "LatinAmerica",
  HT: "LatinAmerica",
  HN: "LatinAmerica",
  JM: "LatinAmerica",
  MQ: "LatinAmerica",
  MX: "LatinAmerica",
  MS: "LatinAmerica",
  NI: "LatinAmerica",
  PA: "LatinAmerica",
  PY: "LatinAmerica",
  PE: "LatinAmerica",
  PR: "LatinAmerica",
  BL: "LatinAmerica",
  KN: "LatinAmerica",
  LC: "LatinAmerica",
  MF: "LatinAmerica",
  VC: "LatinAmerica",
  SX: "LatinAmerica",
  GS: "LatinAmerica",
  SR: "LatinAmerica",
  TT: "LatinAmerica",
  TC: "LatinAmerica",
  UY: "LatinAmerica",
  VI: "LatinAmerica",
  VE: "LatinAmerica",
  GB: "UnitedKingdom",
  IM: "UnitedKingdom",
  AT: "Eurozone",
  AX: "Eurozone",
  BE: "Eurozone",
  CY: "Eurozone",
  EE: "Eurozone",
  FI: "Eurozone",
  FR: "Eurozone",
  DE: "Eurozone",
  GR: "Eurozone",
  IE: "Eurozone",
  IT: "Eurozone",
  LV: "Eurozone",
  LT: "Eurozone",
  LU: "Eurozone",
  MT: "Eurozone",
  NL: "Eurozone",
  PT: "Eurozone",
  SK: "Eurozone",
  SI: "Eurozone",
  ES: "Eurozone",
  AD: "EuropeDeveloped",
  DK: "EuropeDeveloped",
  FO: "EuropeDeveloped",
  GI: "EuropeDeveloped",
  GL: "EuropeDeveloped",
  GG: "EuropeDeveloped",
  IS: "EuropeDeveloped",
  JE: "EuropeDeveloped",
  LI: "EuropeDeveloped",
  MC: "EuropeDeveloped",
  NO: "EuropeDeveloped",
  SM: "EuropeDeveloped",
  SJ: "EuropeDeveloped",
  SE: "EuropeDeveloped",
  CH: "EuropeDeveloped",
  VA: "EuropeDeveloped",
  AL: "EuropeEmerging",
  BY: "EuropeEmerging",
  BA: "EuropeEmerging",
  BG: "EuropeEmerging",
  HR: "EuropeEmerging",
  CZ: "EuropeEmerging",
  HU: "EuropeEmerging",
  MK: "EuropeEmerging",
  MD: "EuropeEmerging",
  PL: "EuropeEmerging",
  RO: "EuropeEmerging",
  RU: "EuropeEmerging",
  RS: "EuropeEmerging",
  ME: "EuropeEmerging",
  TR: "EuropeEmerging",
  UA: "EuropeEmerging",
  DZ: "AfricaME",
  AO: "AfricaME",
  BH: "AfricaME",
  BJ: "AfricaME",
  BW: "AfricaME",
  BV: "AfricaME",
  BF: "AfricaME",
  BI: "AfricaME",
  CM: "AfricaME",
  CV: "AfricaME",
  CF: "AfricaME",
  TD: "AfricaME",
  KM: "AfricaME",
  CG: "AfricaME",
  CD: "AfricaME",
  CI: "AfricaME",
  DJ: "AfricaME",
  EG: "AfricaME",
  TF: "AfricaME",
  GQ: "AfricaME",
  ER: "AfricaME",
  ET: "AfricaME",
  GA: "AfricaME",
  GM: "AfricaME",
  GH: "AfricaME",
  GN: "AfricaME",
  GW: "AfricaME",
  IR: "AfricaME",
  IQ: "AfricaME",
  IL: "AfricaME",
  JO: "AfricaME",
  KE: "AfricaME",
  KW: "AfricaME",
  LB: "AfricaME",
  LS: "AfricaME",
  LR: "AfricaME",
  LY: "AfricaME",
  MG: "AfricaME",
  MW: "AfricaME",
  ML: "AfricaME",
  MR: "AfricaME",
  MU: "AfricaME",
  YT: "AfricaME",
  MA: "AfricaME",
  MZ: "AfricaME",
  NA: "AfricaME",
  NE: "AfricaME",
  NG: "AfricaME",
  OM: "AfricaME",
  QA: "AfricaME",
  RE: "AfricaME",
  RW: "AfricaME",
  ST: "AfricaME",
  SA: "AfricaME",
  SN: "AfricaME",
  SC: "AfricaME",
  SL: "AfricaME",
  SO: "AfricaME",
  ZA: "AfricaME",
  SS: "AfricaME",
  SD: "AfricaME",
  SH: "AfricaME",
  SZ: "AfricaME",
  SY: "AfricaME",
  TZ: "AfricaME",
  TG: "AfricaME",
  TN: "AfricaME",
  UG: "AfricaME",
  AE: "AfricaME",
  PS: "AfricaME",
  EH: "AfricaME",
  YE: "AfricaME",
  ZM: "AfricaME",
  ZW: "AfricaME",
  JP: "Japan",
  AU: "Australasia",
  NZ: "Australasia",
  BN: "AsiaDeveloped",
  PF: "AsiaDeveloped",
  GU: "AsiaDeveloped",
  HK: "AsiaDeveloped",
  MO: "AsiaDeveloped",
  NC: "AsiaDeveloped",
  SG: "AsiaDeveloped",
  KR: "AsiaDeveloped",
  TW: "AsiaDeveloped",
  IO: "AsiaDeveloped",
  AF: "AsiaEmerging",
  AS: "AsiaEmerging",
  AM: "AsiaEmerging",
  AZ: "AsiaEmerging",
  BD: "AsiaEmerging",
  BT: "AsiaEmerging",
  MM: "AsiaEmerging",
  KH: "AsiaEmerging",
  CN: "AsiaEmerging",
  CX: "AsiaEmerging",
  CC: "AsiaEmerging",
  CK: "AsiaEmerging",
  TL: "AsiaEmerging",
  FJ: "AsiaEmerging",
  GE: "AsiaEmerging",
  HM: "AsiaEmerging",
  IN: "AsiaEmerging",
  ID: "AsiaEmerging",
  KZ: "AsiaEmerging",
  KI: "AsiaEmerging",
  KG: "AsiaEmerging",
  LA: "AsiaEmerging",
  MY: "AsiaEmerging",
  MV: "AsiaEmerging",
  MH: "AsiaEmerging",
  FM: "AsiaEmerging",
  MN: "AsiaEmerging",
  NR: "AsiaEmerging",
  NP: "AsiaEmerging",
  NU: "AsiaEmerging",
  NF: "AsiaEmerging",
  KP: "AsiaEmerging",
  MP: "AsiaEmerging",
  PK: "AsiaEmerging",
  // deepcode ignore NoHardcodedPasswords: PW is the country code for Palau
  PW: "AsiaEmerging",
  PG: "AsiaEmerging",
  PH: "AsiaEmerging",
  PN: "AsiaEmerging",
  WS: "AsiaEmerging",
  SB: "AsiaEmerging",
  LK: "AsiaEmerging",
  TJ: "AsiaEmerging",
  TH: "AsiaEmerging",
  TK: "AsiaEmerging",
  TO: "AsiaEmerging",
  TM: "AsiaEmerging",
  TV: "AsiaEmerging",
  UZ: "AsiaEmerging",
  VU: "AsiaEmerging",
  VN: "AsiaEmerging",
  WF: "AsiaEmerging",
};

/**
 * Returns an array of all countries in a given region.
 *
 * @param {Region} region The region to get countries for.
 * @returns {Country[]} The array of countries in the given region.
 */
export const getCountriesInRegion = (region: Region): Country[] => {
  return countryArray.filter((country) => regionOfCountry[country] == region);
};
