import type { Industry } from "./Industry";
import { industryArray } from "./Industry";

/**
 * An array of industry groups in the Morningstar Global Equity Classification Structure.
 */
export const industryGroupArray = [
  "Agriculture",
  "BuildingMaterials",
  "Chemicals",
  "ForestProducts",
  "MetalsMining",
  "Steel",
  "VehiclesParts",
  "FurnishingsFixturesAppliance",
  "HomebuildingConstruction",
  "ManufacturingApparelAccessories",
  "PackagingContainers",
  "PersonalServices",
  "Restaurants",
  "RetailCyclical",
  "TravelLeisure",
  "AssetManagement",
  "Banks",
  "CapitalMarkets",
  "Insurance",
  "DiversifiedFinancialServices",
  "CreditServices",
  "RealEstate",
  "REITs",
  "BeveragesAlcoholic",
  "BeveragesNonAlcoholic",
  "ConsumerPackagedGoods",
  "Education",
  "RetailDefensive",
  "TobaccoProducts",
  "Biotechnology",
  "DrugManufacturers",
  "HealthcarePlans",
  "HealthcareProvidersServices",
  "MedicalDevicesInstruments",
  "MedicalDiagnosticsResearch",
  "MedicalDistribution",
  "UtilitiesIndependentPowerProducers",
  "UtilitiesRegulated",
  "TelecommunicationServices",
  "MediaDiversified",
  "InteractiveMedia",
  "OilGas",
  "OtherEnergySources",
  "AerospaceDefense",
  "BusinessServices",
  "Conglomerates",
  "Construction",
  "FarmHeavyConstructionMachinery",
  "IndustrialDistribution",
  "IndustrialProducts",
  "Transportation",
  "WasteManagement",
  "Software",
  "Hardware",
  "Semiconductors",
] as const;

/**
 * An industry group in the Morningstar Global Equity Classification Structure.
 */
export type IndustryGroup = (typeof industryGroupArray)[number];

/**
 * Checks if a string is a valid industry group.
 * @param s The string to check.
 * @returns True if the string is a valid industry group.
 */
export function isIndustryGroup(s: string): s is IndustryGroup {
  return industryGroupArray.includes(s as IndustryGroup);
}

/**
 * A record of industry group names for each industry group.
 */
export const industryGroupName: Record<IndustryGroup, string> = {
  Agriculture: "Agriculture",
  BuildingMaterials: "Building Materials",
  Chemicals: "Chemicals",
  ForestProducts: "Forest Products",
  MetalsMining: "Metals & Mining",
  Steel: "Steel",
  VehiclesParts: "Vehicles & Parts",
  FurnishingsFixturesAppliance: "Furnishings, Fixtures, & Appliance",
  HomebuildingConstruction: "Homebuilding & Construction",
  ManufacturingApparelAccessories: "Manufacturing – Apparel & Accessories",
  PackagingContainers: "Packaging & Containers",
  PersonalServices: "Personal Services",
  Restaurants: "Restaurants",
  RetailCyclical: "Retail – Cyclical",
  TravelLeisure: "Travel & Leisure",
  AssetManagement: "Asset Management",
  Banks: "Banks",
  CapitalMarkets: "Capital Markets",
  Insurance: "Insurance",
  DiversifiedFinancialServices: "Diversified Financial Services",
  CreditServices: "Credit Services",
  RealEstate: "Real Estate",
  REITs: "REITs",
  BeveragesAlcoholic: "Beverages – Alcoholic",
  BeveragesNonAlcoholic: "Beverages – Non-Alcoholic",
  ConsumerPackagedGoods: "Consumer Packaged Goods",
  Education: "Education",
  RetailDefensive: "Retail – Defensive",
  TobaccoProducts: "Tobacco Products",
  Biotechnology: "Biotechnology",
  DrugManufacturers: "Drug Manufacturers",
  HealthcarePlans: "Healthcare Plans",
  HealthcareProvidersServices: "Health Care Providers & Services",
  MedicalDevicesInstruments: "Medical Devices & Instruments",
  MedicalDiagnosticsResearch: "Medical Diagnostics & Research",
  MedicalDistribution: "Medical Distribution",
  UtilitiesIndependentPowerProducers: "Utilities – Independent Power Producers",
  UtilitiesRegulated: "Utilities – Regulated",
  TelecommunicationServices: "Telecommunication Services",
  MediaDiversified: "Media – Diversified",
  InteractiveMedia: "Interactive Media",
  OilGas: "Oil & Gas",
  OtherEnergySources: "Other Energy Sources",
  AerospaceDefense: "Aerospace & Defense",
  BusinessServices: "Business Services",
  Conglomerates: "Conglomerates",
  Construction: "Construction",
  FarmHeavyConstructionMachinery: "Farm & Heavy Construction Machinery",
  IndustrialDistribution: "Industrial Distribution",
  IndustrialProducts: "Industrial Products",
  Transportation: "Transportation",
  WasteManagement: "Waste Management",
  Software: "Software",
  Hardware: "Hardware",
  Semiconductors: "Semiconductors",
};

/**
 * A record associating each industry with its industry group.
 */
export const groupOfIndustry: Record<Industry, IndustryGroup> = {
  AgriculturalInputs: "Agriculture",
  BuildingMaterials: "BuildingMaterials",
  Chemicals: "Chemicals",
  SpecialtyChemicals: "Chemicals",
  LumberWoodProduction: "ForestProducts",
  PaperPaperProducts: "ForestProducts",
  Aluminum: "MetalsMining",
  Copper: "MetalsMining",
  OtherIndustrialMetalsMining: "MetalsMining",
  Gold: "MetalsMining",
  Silver: "MetalsMining",
  OtherPreciousMetalsMining: "MetalsMining",
  CokingCoal: "Steel",
  Steel: "Steel",
  AutoTruckDealerships: "VehiclesParts",
  AutoManufacturers: "VehiclesParts",
  AutoParts: "VehiclesParts",
  RecreationalVehicles: "VehiclesParts",
  FurnishingsFixturesAppliances: "FurnishingsFixturesAppliance",
  ResidentialConstruction: "HomebuildingConstruction",
  TextileManufacturing: "ManufacturingApparelAccessories",
  ApparelManufacturing: "ManufacturingApparelAccessories",
  FootwearAccessories: "ManufacturingApparelAccessories",
  PackagingContainers: "PackagingContainers",
  PersonalServices: "PersonalServices",
  Restaurants: "Restaurants",
  ApparelRetail: "RetailCyclical",
  DepartmentStores: "RetailCyclical",
  HomeImprovementRetail: "RetailCyclical",
  LuxuryGoods: "RetailCyclical",
  InternetRetail: "RetailCyclical",
  SpecialtyRetail: "RetailCyclical",
  Gambling: "TravelLeisure",
  Leisure: "TravelLeisure",
  Lodging: "TravelLeisure",
  ResortsCasinos: "TravelLeisure",
  TravelServices: "TravelLeisure",
  AssetManagement: "AssetManagement",
  BanksDiversified: "Banks",
  BanksRegional: "Banks",
  MortgageFinance: "Banks",
  CapitalMarkets: "CapitalMarkets",
  FinancialDataStockExchanges: "CapitalMarkets",
  InsuranceLife: "Insurance",
  InsurancePropertyCasualty: "Insurance",
  InsuranceReinsurance: "Insurance",
  InsuranceSpecialty: "Insurance",
  InsuranceBrokers: "Insurance",
  InsuranceDiversified: "Insurance",
  ShellCompanies: "DiversifiedFinancialServices",
  FinancialConglomerates: "DiversifiedFinancialServices",
  CreditServices: "CreditServices",
  RealEstateDevelopment: "RealEstate",
  RealEstateServices: "RealEstate",
  RealEstateDiversified: "RealEstate",
  REITHealthcareFacilities: "REITs",
  REITHotelMotel: "REITs",
  REITIndustrial: "REITs",
  REITOffice: "REITs",
  REITResidential: "REITs",
  REITRetail: "REITs",
  REITMortgage: "REITs",
  REITSpecialty: "REITs",
  REITDiversified: "REITs",
  BeveragesBrewers: "BeveragesAlcoholic",
  BeveragesWineriesDistilleries: "BeveragesAlcoholic",
  BeveragesNonAlcoholic: "BeveragesNonAlcoholic",
  Confectioners: "ConsumerPackagedGoods",
  FarmProducts: "ConsumerPackagedGoods",
  HouseholdPersonalProducts: "ConsumerPackagedGoods",
  PackagedFoods: "ConsumerPackagedGoods",
  EducationTrainingServices: "Education",
  DiscountStores: "RetailDefensive",
  FoodDistribution: "RetailDefensive",
  GroceryStores: "RetailDefensive",
  Tobacco: "TobaccoProducts",
  Biotechnology: "Biotechnology",
  DrugManufacturersGeneral: "DrugManufacturers",
  DrugManufacturersSpecialtyGeneric: "DrugManufacturers",
  HealthcarePlans: "HealthcarePlans",
  MedicalCareFacilities: "HealthcareProvidersServices",
  PharmaceuticalRetailers: "HealthcareProvidersServices",
  HealthInformationServices: "HealthcareProvidersServices",
  MedicalDevices: "MedicalDevicesInstruments",
  MedicalInstrumentsSupplies: "MedicalDevicesInstruments",
  DiagnosticsResearch: "MedicalDiagnosticsResearch",
  MedicalDistribution: "MedicalDistribution",
  UtilitiesIndependentPowerProducers: "UtilitiesIndependentPowerProducers",
  UtilitiesRenewable: "UtilitiesIndependentPowerProducers",
  UtilitiesRegulatedWater: "UtilitiesRegulated",
  UtilitiesRegulatedElectric: "UtilitiesRegulated",
  UtilitiesRegulatedGas: "UtilitiesRegulated",
  UtilitiesDiversified: "UtilitiesRegulated",
  TelecomServices: "TelecommunicationServices",
  AdvertisingAgencies: "MediaDiversified",
  Publishing: "MediaDiversified",
  Broadcasting: "MediaDiversified",
  Entertainment: "MediaDiversified",
  InternetContentInformation: "InteractiveMedia",
  ElectronicGamingMultimedia: "InteractiveMedia",
  OilGasDrilling: "OilGas",
  OilGasEP: "OilGas",
  OilGasIntegrated: "OilGas",
  OilGasMidstream: "OilGas",
  OilGasRefiningMarketing: "OilGas",
  OilGasEquipmentServices: "OilGas",
  ThermalCoal: "OtherEnergySources",
  Uranium: "OtherEnergySources",
  AerospaceDefense: "AerospaceDefense",
  SpecialtyBusinessServices: "BusinessServices",
  ConsultingServices: "BusinessServices",
  RentalLeasingServices: "BusinessServices",
  SecurityProtectionServices: "BusinessServices",
  StaffingEmploymentServices: "BusinessServices",
  Conglomerates: "Conglomerates",
  EngineeringConstruction: "Construction",
  InfrastructureOperations: "Construction",
  BuildingProductsEquipment: "Construction",
  FarmHeavyConstructionMachinery: "FarmHeavyConstructionMachinery",
  IndustrialDistribution: "IndustrialDistribution",
  BusinessEquipmentSupplies: "IndustrialProducts",
  SpecialtyIndustrialMachinery: "IndustrialProducts",
  MetalFabrication: "IndustrialProducts",
  PollutionTreatmentControls: "IndustrialProducts",
  ToolsAccessories: "IndustrialProducts",
  ElectricalEquipmentParts: "IndustrialProducts",
  AirportsAirServices: "Transportation",
  Airlines: "Transportation",
  Railroads: "Transportation",
  MarineShipping: "Transportation",
  Trucking: "Transportation",
  IntegratedFreightLogistics: "Transportation",
  WasteManagement: "WasteManagement",
  InformationTechnologyServices: "Software",
  SoftwareApplication: "Software",
  SoftwareInfrastructure: "Software",
  CommunicationEquipment: "Hardware",
  ComputerHardware: "Hardware",
  ConsumerElectronics: "Hardware",
  ElectronicComponents: "Hardware",
  ElectronicsComputerDistribution: "Hardware",
  ScientificTechnicalInstruments: "Hardware",
  SemiconductorEquipmentMaterials: "Semiconductors",
  Semiconductors: "Semiconductors",
  Solar: "Semiconductors",
};

/**
 * Returns an array of all industries in a industry group.
 * @param industryGroup The industry group to get industries for.
 * @returns The array of industries in the industry group.
 */
export const getIndustriesInGroup = (industryGroup: IndustryGroup): Industry[] => {
  return industryArray.filter((industry) => groupOfIndustry[industry] == industryGroup);
};
