import { Currency } from "../Currency.js";
import { Country } from "../geo/Country.js";
import { Industry } from "../gics/Industry.js";
import { MSCIESGRating } from "../ratings/MSCI.js";
import { Size } from "../stylebox/Size.js";
import { Style } from "../stylebox/Style.js";

export class Stock {
  ticker: string;
  name: string;
  isin: string;
  country: Country;
  industry?: Industry;
  size?: Size;
  style?: Style;
  morningstarId?: string;
  morningstarLastFetch?: Date;
  starRating?: number;
  dividendYieldPercent?: number;
  priceEarningRatio?: number;
  currency?: Currency;
  lastClose?: number;
  morningstarFairValue?: number;
  marketCap?: number;
  low52w?: number;
  high52w?: number;
  marketScreenerId?: string;
  marketScreenerLastFetch?: Date;
  analystConsensus?: number;
  analystCount?: number;
  analystTargetPrice?: number;
  msciId?: string;
  msciLastFetch?: Date;
  msciESGRating?: MSCIESGRating;
  msciTemperature?: number;
  ric?: string;
  refinitivLastFetch?: Date;
  refinitivESGScore?: number;
  refinitivEmissions?: number;
  spId?: number;
  spLastFetch?: Date;
  spESGScore?: number;
  sustainalyticsId?: string;
  sustainalyticsESGRisk?: number;
}
