services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:alpine
    restart: unless-stopped
    user: 70:70
    cap_drop:
      - all
    cap_add:
      - CHOWN
    security_opt:
      - no-new-privileges
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: "rating-tracker"
      POSTGRES_USER: "rating-tracker"
      POSTGRES_PASSWORD_FILE: /var/lib/postgresql/pgpass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/pgpass:/var/lib/postgresql/pgpass
    shm_size: "256mb"

  signal:
    container_name: signal
    hostname: signal
    image: bbernhard/signal-cli-rest-api
    environment:
      - MODE=native
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./signal-cli:/home/.local/share/signal-cli
