export const industryArray = [
  "AgriculturalInputs",
  "BuildingMaterials",
  "Chemicals",
  "SpecialtyChemicals",
  "LumberWoodProduction",
  "PaperPaperProducts",
  "Aluminum",
  "Copper",
  "OtherIndustrialMetalsMining",
  "Gold",
  "Silver",
  "OtherPreciousMetalsMining",
  "CokingCoal",
  "Steel",
  "AutoTruckDealerships",
  "AutoManufacturers",
  "AutoParts",
  "RecreationalVehicles",
  "FurnishingsFixturesAppliances",
  "ResidentialConstruction",
  "TextileManufacturing",
  "ApparelManufacturing",
  "FootwearAccessories",
  "PackagingContainers",
  "PersonalServices",
  "Restaurants",
  "ApparelRetail",
  "DepartmentStores",
  "HomeImprovementRetail",
  "LuxuryGoods",
  "InternetRetail",
  "SpecialtyRetail",
  "Gambling",
  "Leisure",
  "Lodging",
  "ResortsCasinos",
  "TravelServices",
  "AssetManagement",
  "BanksDiversified",
  "BanksRegional",
  "MortgageFinance",
  "CapitalMarkets",
  "FinancialDataStockExchanges",
  "InsuranceLife",
  "InsurancePropertyCasualty",
  "InsuranceReinsurance",
  "InsuranceSpecialty",
  "InsuranceBrokers",
  "InsuranceDiversified",
  "ShellCompanies",
  "FinancialConglomerates",
  "CreditServices",
  "RealEstateDevelopment",
  "RealEstateServices",
  "RealEstateDiversified",
  "REITHealthcareFacilities",
  "REITHotelMotel",
  "REITIndustrial",
  "REITOffice",
  "REITResidential",
  "REITRetail",
  "REITMortgage",
  "REITSpecialty",
  "REITDiversified",
  "BeveragesBrewers",
  "BeveragesWineriesDistilleries",
  "BeveragesNonAlcoholic",
  "Confectioners",
  "FarmProducts",
  "HouseholdPersonalProducts",
  "PackagedFoods",
  "EducationTrainingServices",
  "DiscountStores",
  "FoodDistribution",
  "GroceryStores",
  "Tobacco",
  "Biotechnology",
  "DrugManufacturersGeneral",
  "DrugManufacturersSpecialtyGeneric",
  "HealthcarePlans",
  "MedicalCareFacilities",
  "PharmaceuticalRetailers",
  "HealthInformationServices",
  "MedicalDevices",
  "MedicalInstrumentsSupplies",
  "DiagnosticsResearch",
  "MedicalDistribution",
  "UtilitiesIndependentPowerProducers",
  "UtilitiesRenewable",
  "UtilitiesRegulatedWater",
  "UtilitiesRegulatedElectric",
  "UtilitiesRegulatedGas",
  "UtilitiesDiversified",
  "TelecomServices",
  "AdvertisingAgencies",
  "Publishing",
  "Broadcasting",
  "Entertainment",
  "InternetContentInformation",
  "ElectronicGamingMultimedia",
  "OilGasDrilling",
  "OilGasEP",
  "OilGasIntegrated",
  "OilGasMidstream",
  "OilGasRefiningMarketing",
  "OilGasEquipmentServices",
  "ThermalCoal",
  "Uranium",
  "AerospaceDefense",
  "SpecialtyBusinessServices",
  "ConsultingServices",
  "RentalLeasingServices",
  "SecurityProtectionServices",
  "StaffingEmploymentServices",
  "Conglomerates",
  "EngineeringConstruction",
  "InfrastructureOperations",
  "BuildingProductsEquipment",
  "FarmHeavyConstructionMachinery",
  "IndustrialDistribution",
  "BusinessEquipmentSupplies",
  "SpecialtyIndustrialMachinery",
  "MetalFabrication",
  "PollutionTreatmentControls",
  "ToolsAccessories",
  "ElectricalEquipmentParts",
  "AirportsAirServices",
  "Airlines",
  "Railroads",
  "MarineShipping",
  "Trucking",
  "IntegratedFreightLogistics",
  "WasteManagement",
  "InformationTechnologyServices",
  "SoftwareApplication",
  "SoftwareInfrastructure",
  "CommunicationEquipment",
  "ComputerHardware",
  "ConsumerElectronics",
  "ElectronicComponents",
  "ElectronicsComputerDistribution",
  "ScientificTechnicalInstruments",
  "SemiconductorEquipmentMaterials",
  "Semiconductors",
  "Solar",
] as const;

export type Industry = typeof industryArray[number];

export function isIndustry(s: string): s is Industry {
  return industryArray.includes(s as Industry);
}

export const industryName: Record<Industry, string> = {
  AgriculturalInputs: "Agricultural Inputs",
  BuildingMaterials: "Building Materials",
  Chemicals: "Chemicals",
  SpecialtyChemicals: "Specialty Chemicals",
  LumberWoodProduction: "Lumber & Wood Production",
  PaperPaperProducts: "Paper & Paper Products",
  Aluminum: "Aluminum",
  Copper: "Copper",
  OtherIndustrialMetalsMining: "Other Industrial Metals & Mining",
  Gold: "Gold",
  Silver: "Silver",
  OtherPreciousMetalsMining: "Other Precious Metals & Mining",
  CokingCoal: "Coking Coal",
  Steel: "Steel",
  AutoTruckDealerships: "Auto & Truck Dealerships",
  AutoManufacturers: "Auto Manufacturers",
  AutoParts: "Auto Parts",
  RecreationalVehicles: "Recreational Vehicles",
  FurnishingsFixturesAppliances: "Furnishings, Fixtures, & Appliances",
  ResidentialConstruction: "Residential Construction",
  TextileManufacturing: "Textile Manufacturing",
  ApparelManufacturing: "Apparel Manufacturing",
  FootwearAccessories: "Footwear & Accessories",
  PackagingContainers: "Packaging & Containers",
  PersonalServices: "Personal Services",
  Restaurants: "Restaurants",
  ApparelRetail: "Apparel Retail",
  DepartmentStores: "Department Stores",
  HomeImprovementRetail: "Home Improvement Retail",
  LuxuryGoods: "Luxury Goods",
  InternetRetail: "Internet Retail",
  SpecialtyRetail: "Specialty Retail",
  Gambling: "Gambling",
  Leisure: "Leisure",
  Lodging: "Lodging",
  ResortsCasinos: "Resorts & Casinos",
  TravelServices: "TravelServices",
  AssetManagement: "Asset Management",
  BanksDiversified: "Banks – Diversified",
  BanksRegional: "Banks – Regional",
  MortgageFinance: "Mortgage Finance",
  CapitalMarkets: "Capital Markets",
  FinancialDataStockExchanges: "Financial Data & Stock Exchanges",
  InsuranceLife: "Insurance – Life",
  InsurancePropertyCasualty: "Insurance – Property & Casualty",
  InsuranceReinsurance: "Insurance – Reinsurance",
  InsuranceSpecialty: "Insurance – Specialty",
  InsuranceBrokers: "Insurance – Brokers",
  InsuranceDiversified: "Insurance – Diversified",
  ShellCompanies: "Shell Companies",
  FinancialConglomerates: "Financial Conglomerates",
  CreditServices: "Credit Services",
  RealEstateDevelopment: "Real Estate – Development",
  RealEstateServices: "Real Estate Services",
  RealEstateDiversified: "Real Estate – Diversified",
  REITHealthcareFacilities: "REIT – Healthcare Facilities",
  REITHotelMotel: "REIT – Hotel & Motel",
  REITIndustrial: "REIT – Industrial",
  REITOffice: "REIT – Office",
  REITResidential: "REIT – Residential",
  REITRetail: "REIT – Retail",
  REITMortgage: "REIT – Mortgage",
  REITSpecialty: "REIT – Specialty",
  REITDiversified: "REIT – Diversified",
  BeveragesBrewers: "Beverages – Brewers",
  BeveragesWineriesDistilleries: "Beverages – Wineries & Distilleries",
  BeveragesNonAlcoholic: "Beverages – Non-Alcoholic",
  Confectioners: "Confectioners",
  FarmProducts: "Farm Products",
  HouseholdPersonalProducts: "Household & Personal Products",
  PackagedFoods: "Packaged Foods",
  EducationTrainingServices: "Education & Training Services",
  DiscountStores: "Discount Stores",
  FoodDistribution: "Food Distribution",
  GroceryStores: "Grocery Stores",
  Tobacco: "Tobacco",
  Biotechnology: "Biotechnology",
  DrugManufacturersGeneral: "Drug Manufacturers – General",
  DrugManufacturersSpecialtyGeneric: "Drug Manufacturers – Specialty & Generic",
  HealthcarePlans: "Healthcare Plans",
  MedicalCareFacilities: "Medical Care Facilities",
  PharmaceuticalRetailers: "Pharmaceutical Retailers",
  HealthInformationServices: "Health Information Services",
  MedicalDevices: "Medical Devices",
  MedicalInstrumentsSupplies: "Medical Instruments & Supplies",
  DiagnosticsResearch: "Diagnostics & Research",
  MedicalDistribution: "Medical Distribution",
  UtilitiesIndependentPowerProducers: "Utilities – Independent Power Producers",
  UtilitiesRenewable: "Utilities – Renewable",
  UtilitiesRegulatedWater: "Utilities – Regulated Water",
  UtilitiesRegulatedElectric: "Utilities – Regulated Electric",
  UtilitiesRegulatedGas: "Utilities – Regulated Gas",
  UtilitiesDiversified: "Utilities – Diversified",
  TelecomServices: "Telecom Services",
  AdvertisingAgencies: "Advertising Agencies",
  Publishing: "Publishing",
  Broadcasting: "Broadcasting",
  Entertainment: "Entertainment",
  InternetContentInformation: "Internet Content & Information",
  ElectronicGamingMultimedia: "Electronic Gaming & Multimedia",
  OilGasDrilling: "Oil & Gas Drilling",
  OilGasEP: "Oil & Gas E&P",
  OilGasIntegrated: "Oil & Gas Integrated",
  OilGasMidstream: "Oil & Gas Midstream",
  OilGasRefiningMarketing: "Oil & Gas Refining & Marketing",
  OilGasEquipmentServices: "Oil & Gas Equipment & Services",
  ThermalCoal: "Thermal Coal",
  Uranium: "Uranium",
  AerospaceDefense: "Aerospace & Defense",
  SpecialtyBusinessServices: "Specialty Business Services",
  ConsultingServices: "Consulting Services",
  RentalLeasingServices: "Rental & Leasing Services",
  SecurityProtectionServices: "Security & Protection Services",
  StaffingEmploymentServices: "Staffing & Employment Services",
  Conglomerates: "Conglomerates",
  EngineeringConstruction: "Engineering & Construction",
  InfrastructureOperations: "Infrastructure Operations",
  BuildingProductsEquipment: "Building Products & Equipment",
  FarmHeavyConstructionMachinery: "Farm & Heavy Construction Machinery",
  IndustrialDistribution: "Industrial Distribution",
  BusinessEquipmentSupplies: "Business Equipment & Supplies",
  SpecialtyIndustrialMachinery: "Specialty Industrial Machinery",
  MetalFabrication: "Metal Fabrication",
  PollutionTreatmentControls: "Pollution & Treatment Controls",
  ToolsAccessories: "Tools & Accessories",
  ElectricalEquipmentParts: "Electrical Equipment & Parts",
  AirportsAirServices: "Airports & Air Services",
  Airlines: "Airlines",
  Railroads: "Railroads",
  MarineShipping: "Marine Shipping",
  Trucking: "Trucking",
  IntegratedFreightLogistics: "Integrated Freight & Logistics",
  WasteManagement: "Waste Management",
  InformationTechnologyServices: "Information Technology Services",
  SoftwareApplication: "Software – Application",
  SoftwareInfrastructure: "Software – Infrastructure",
  CommunicationEquipment: "Communication Equipment",
  ComputerHardware: "Computer Hardware",
  ConsumerElectronics: "Consumer Electronics",
  ElectronicComponents: "Electronic Components",
  ElectronicsComputerDistribution: "Electronics & Computer Distribution",
  ScientificTechnicalInstruments: "Scientific & Technical Instruments",
  SemiconductorEquipmentMaterials: "Semiconductor Equipment & Materials",
  Semiconductors: "Semiconductors",
  Solar: "Solar",
};
