export const countryArray = [
  "AF",
  "AX",
  "AL",
  "DZ",
  "AS",
  "AD",
  "AO",
  "AI",
  "AG",
  "AR",
  "AM",
  "AW",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BM",
  "BT",
  "BO",
  "BQ",
  "BA",
  "BW",
  "BV",
  "BR",
  "IO",
  "BN",
  "BG",
  "BF",
  "BI",
  "CV",
  "KH",
  "CM",
  "CA",
  "KY",
  "CF",
  "TD",
  "CL",
  "CN",
  "CX",
  "CC",
  "CO",
  "KM",
  "CG",
  "CD",
  "CK",
  "CR",
  "CI",
  "HR",
  "CU",
  "CW",
  "CY",
  "CZ",
  "DK",
  "DJ",
  "DM",
  "DO",
  "EC",
  "EG",
  "SV",
  "GQ",
  "ER",
  "EE",
  "SZ",
  "ET",
  "FK",
  "FO",
  "FJ",
  "FI",
  "FR",
  "GF",
  "PF",
  "TF",
  "GA",
  "GM",
  "GE",
  "DE",
  "GH",
  "GI",
  "GR",
  "GL",
  "GD",
  "GP",
  "GU",
  "GT",
  "GG",
  "GN",
  "GW",
  "GY",
  "HT",
  "HM",
  "VA",
  "HN",
  "HK",
  "HU",
  "IS",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IM",
  "IL",
  "IT",
  "JM",
  "JP",
  "JE",
  "JO",
  "KZ",
  "KE",
  "KI",
  "KR",
  "KP",
  "KW",
  "KG",
  "LA",
  "LV",
  "LB",
  "LS",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MO",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MH",
  "MQ",
  "MR",
  "MU",
  "YT",
  "MX",
  "FM",
  "MD",
  "MC",
  "MN",
  "ME",
  "MS",
  "MA",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NL",
  "NC",
  "NZ",
  "NI",
  "NE",
  "NG",
  "NU",
  "NF",
  "MK",
  "MP",
  "NO",
  "OM",
  "PK",
  "PW",
  "PS",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PN",
  "PL",
  "PT",
  "PR",
  "QA",
  "RE",
  "RO",
  "RU",
  "RW",
  "BL",
  "SH",
  "KN",
  "LC",
  "MF",
  "PM",
  "VC",
  "WS",
  "SM",
  "ST",
  "SA",
  "SN",
  "RS",
  "SC",
  "SL",
  "SG",
  "SX",
  "SK",
  "SI",
  "SB",
  "SO",
  "ZA",
  "GS",
  "SS",
  "ES",
  "LK",
  "SD",
  "SR",
  "SJ",
  "SE",
  "CH",
  "SY",
  "TW",
  "TJ",
  "TZ",
  "TH",
  "TL",
  "TG",
  "TK",
  "TO",
  "TT",
  "TN",
  "TR",
  "TM",
  "TC",
  "TV",
  "UG",
  "UA",
  "AE",
  "GB",
  "US",
  "UM",
  "UY",
  "UZ",
  "VU",
  "VE",
  "VN",
  "VG",
  "VI",
  "WF",
  "EH",
  "YE",
  "ZM",
  "ZW",
] as const;

export type Country = typeof countryArray[number];

export function isCountry(s: string): s is Country {
  return countryArray.includes(s as Country);
}

export const regionArray = [
  "NorthAmerica",
  "LatinAmerica",
  "UnitedKingdom",
  "Eurozone",
  "EuropeDeveloped",
  "EuropeEmerging",
  "AfricaME",
  "Japan",
  "Australasia",
  "AsiaDeveloped",
  "AsiaEmerging",
] as const;

export type Region = typeof regionArray[number];

export function isRegion(s: string): s is Region {
  return regionArray.includes(s as Region);
}

export const superRegionArray = ["Americas", "EMEA", "Asia"] as const;

export type SuperRegion = typeof superRegionArray[number];

export function isSuperRegion(s: string): s is SuperRegion {
  return superRegionArray.includes(s as SuperRegion);
}

export const industryArray = [
  "AgriculturalInputs",
  "BuildingMaterials",
  "Chemicals",
  "SpecialtyChemicals",
  "LumberWoodProduction",
  "PaperPaperProducts",
  "Aluminum",
  "Copper",
  "OtherIndustrialMetalsMining",
  "Gold",
  "Silver",
  "OtherPreciousMetalsMining",
  "CokingCoal",
  "Steel",
  "AutoTruckDealerships",
  "AutoManufacturers",
  "AutoParts",
  "RecreationalVehicles",
  "FurnishingsFixturesAppliances",
  "ResidentialConstruction",
  "TextileManufacturing",
  "ApparelManufacturing",
  "FootwearAccessories",
  "PackagingContainers",
  "PersonalServices",
  "Restaurants",
  "ApparelRetail",
  "DepartmentStores",
  "HomeImprovementRetail",
  "LuxuryGoods",
  "InternetRetail",
  "SpecialtyRetail",
  "Gambling",
  "Leisure",
  "Lodging",
  "ResortsCasinos",
  "TravelServices",
  "AssetManagement",
  "BanksDiversified",
  "BanksRegional",
  "MortgageFinance",
  "CapitalMarkets",
  "FinancialDataStockExchanges",
  "InsuranceLife",
  "InsurancePropertyCasualty",
  "InsuranceReinsurance",
  "InsuranceSpecialty",
  "InsuranceBrokers",
  "InsuranceDiversified",
  "ShellCompanies",
  "FinancialConglomerates",
  "CreditServices",
  "RealEstateDevelopment",
  "RealEstateServices",
  "RealEstateDiversified",
  "REITHealthcareFacilities",
  "REITHotelMotel",
  "REITIndustrial",
  "REITOffice",
  "REITResidential",
  "REITRetail",
  "REITMortgage",
  "REITSpecialty",
  "REITDiversified",
  "BeveragesBrewers",
  "BeveragesWineriesDistilleries",
  "BeveragesNonAlcoholic",
  "Confectioners",
  "FarmProducts",
  "HouseholdPersonalProducts",
  "PackagedFoods",
  "EducationTrainingServices",
  "DiscountStores",
  "FoodDistribution",
  "GroceryStores",
  "Tobacco",
  "Biotechnology",
  "DrugManufacturersGeneral",
  "DrugManufacturersSpecialtyGeneric",
  "HealthcarePlans",
  "MedicalCareFacilities",
  "PharmaceuticalRetailers",
  "HealthInformationServices",
  "MedicalDevices",
  "MedicalInstrumentsSupplies",
  "DiagnosticsResearch",
  "MedicalDistribution",
  "UtilitiesIndependentPowerProducers",
  "UtilitiesRenewable",
  "UtilitiesRegulatedWater",
  "UtilitiesRegulatedElectric",
  "UtilitiesRegulatedGas",
  "UtilitiesDiversified",
  "TelecomServices",
  "AdvertisingAgencies",
  "Publishing",
  "Broadcasting",
  "Entertainment",
  "InternetContentInformation",
  "ElectronicGamingMultimedia",
  "OilGasDrilling",
  "OilGasEP",
  "OilGasIntegrated",
  "OilGasMidstream",
  "OilGasRefiningMarketing",
  "OilGasEquipmentServices",
  "ThermalCoal",
  "Uranium",
  "AerospaceDefense",
  "SpecialtyBusinessServices",
  "ConsultingServices",
  "RentalLeasingServices",
  "SecurityProtectionServices",
  "StaffingEmploymentServices",
  "Conglomerates",
  "EngineeringConstruction",
  "InfrastructureOperations",
  "BuildingProductsEquipment",
  "FarmHeavyConstructionMachinery",
  "IndustrialDistribution",
  "BusinessEquipmentSupplies",
  "SpecialtyIndustrialMachinery",
  "MetalFabrication",
  "PollutionTreatmentControls",
  "ToolsAccessories",
  "ElectricalEquipmentParts",
  "AirportsAirServices",
  "Airlines",
  "Railroads",
  "MarineShipping",
  "Trucking",
  "IntegratedFreightLogistics",
  "WasteManagement",
  "InformationTechnologyServices",
  "SoftwareApplication",
  "SoftwareInfrastructure",
  "CommunicationEquipment",
  "ComputerHardware",
  "ConsumerElectronics",
  "ElectronicComponents",
  "ElectronicsComputerDistribution",
  "ScientificTechnicalInstruments",
  "SemiconductorEquipmentMaterials",
  "Semiconductors",
  "Solar",
] as const;

export type Industry = typeof industryArray[number];

export function isIndustry(s: string): s is Industry {
  return industryArray.includes(s as Industry);
}

export const industryGroupArray = [
  "Agriculture",
  "BuildingMaterials",
  "Chemicals",
  "ForestProducts",
  "MetalsMining",
  "Steel",
  "VehiclesParts",
  "FurnishingsFixturesAppliance",
  "HomebuildingConstruction",
  "ManufacturingApparelAccessories",
  "PackagingContainers",
  "PersonalServices",
  "Restaurants",
  "RetailCyclical",
  "TravelLeisure",
  "AssetManagement",
  "Banks",
  "CapitalMarkets",
  "Insurance",
  "DiversifiedFinancialServices",
  "CreditServices",
  "RealEstate",
  "REITs",
  "BeveragesAlcoholic",
  "BeveragesNonAlcoholic",
  "ConsumerPackagedGoods",
  "Education",
  "RetailDefensive",
  "TobaccoProducts",
  "Biotechnology",
  "DrugManufacturers",
  "HealthcarePlans",
  "HealthcareProvidersServices",
  "MedicalDevicesInstruments",
  "MedicalDiagnosticsResearch",
  "MedicalDistribution",
  "UtilitiesIndependentPowerProducers",
  "UtilitiesRegulated",
  "TelecommunicationServices",
  "MediaDiversified",
  "InteractiveMedia",
  "OilGas",
  "OtherEnergySources",
  "AerospaceDefense",
  "BusinessServices",
  "Conglomerates",
  "Construction",
  "FarmHeavyConstructionMachinery",
  "IndustrialDistribution",
  "IndustrialProducts",
  "Transportation",
  "WasteManagement",
  "Software",
  "Hardware",
  "Semiconductors",
] as const;

export type IndustryGroup = typeof industryGroupArray[number];

export function isIndustryGroup(s: string): s is IndustryGroup {
  return industryGroupArray.includes(s as IndustryGroup);
}

export const sectorArray = [
  "BasicMaterials",
  "ConsumerCyclical",
  "FinancialServices",
  "RealEstate",
  "ConsumerDefensive",
  "HealthCare",
  "Utilities",
  "CommunicationServices",
  "Energy",
  "Industrials",
  "Technology",
] as const;

export type Sector = typeof sectorArray[number];

export function isSector(s: string): s is Sector {
  return sectorArray.includes(s as Sector);
}

export const superSectorArray = ["Cyclical", "Defensive", "Sensitive"] as const;

export type SuperSector = typeof superSectorArray[number];

export function isSuperSector(s: string): s is SuperSector {
  return superSectorArray.includes(s as SuperSector);
}

export const sizeArray = ["Small", "Mid", "Large"] as const;

export type Size = typeof sizeArray[number];

export function isSize(s: string): s is Size {
  return sizeArray.includes(s as Size);
}

export const sortableAttributeArray = [
  "name",
  "size",
  "style",
  "starRating",
  "dividendYieldPercent",
  "priceEarningRatio",
] as const;

export type SortableAttribute = typeof sortableAttributeArray[number];

export const styleArray = ["Value", "Blend", "Growth"] as const;

export type Style = typeof styleArray[number];

export function isStyle(s: string): s is Style {
  return styleArray.includes(s as Style);
}
